### PR TITLE
Code cleanup and improved hitbox visualization

### PR DESCRIPTION
**Pull request by TheSmartKid**
Cleaned up formatting and indentation
Updated to the latest version of the code-mod-framework
Now dynamically adjusts the number of effects drawn for extended hitboxes, instead of always making 4
Changed effect colors to be more distinct and follow a more logical progression (red, orange, yellow, green, light blue, blue, purple, pink)
Saturation of the effect colors now scales with hitbox damage

Tested with Atmosphere 0.8.10 and SaltyNX with multiple characters, everything works as intended

### CODE REVIEW

**Comment by jugeeya** [comment]
Looks great, thanks. I'll have to test for myself in-game, but in the meantime:

- These tabs do look quite large, don't they? I feel like they don't conform to any sort of standard I've seen.
- https://github.com/jugeeya/UltimateTrainingModpack/blob/69d35361bba02d2a0e7f7a71535e65c2c91ccd1e/source/hitbox_visualizer.hpp#L49 Does this need to have the L2CAgent* as a parameter?

- Is it possible to keep naming schemes in snake_case rather than camelCase (in your code like with `xDist`, etc...) This is super nit, so don't worry.

**Comment by TheSmartKid** [comment]
- The tab sizes on GitHub are 8 spaces wide by default, but you can change that to a more sensible number by appending ?ts=4 to any GitHub URL. The tabs will also display correctly if you open files locally.
- I did some more refactoring, so the effect color is now calculated in ATTACK_replace() and passed as an argument to generate_hitbox_effects. This will also make it easier to implement grab box and detect box visualizations later.
- I moved my helper functions to useful_visual.h, and moved Hash40 and Vector3f to useful.h.
- I changed the return value back to bool. We should probably also make the same change in the code-mod-framework.
- I increased the base saturation of the colors a bit more.

**Comment by jugeeya** [comment]
Awesome, awesome. I'll merge as soon as I can test it out (later tonight PST). Only nit I have is that :
https://github.com/jugeeya/UltimateTrainingModpack/blob/dd6237132b3586cabbd32b9a0784e8244dac5318/source/hitbox_visualizer.hpp#L131
should probably be a constant (`#define` or otherwise) at the top of the file.

The calculated knockback seems like a very interesting idea, I like it a lot.

**Comment by jugeeya** [comment]
2019052818164600-0E7DF678130F4F0FA2C88AE72B47AFDF

Love the way this looks. The extended hitboxes change (varying the number of effects based on distance and other factors) is incredible.

**Pull request merged**
